Fix unable to edit schedules with number only name
When adding a new schedule with a numbers only name `1234` and daily
re occurrence and trying to edit the new schedule than a:
```
TypeError: e.replace is not a function
```
occurs because name is a number and not a string.

To fix that name.toString() is called to explicitly cast it to string.